# Generated by Django 5.2.6 on 2025-09-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseversion',
            old_name='created_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='courseversion',
            old_name='syllabus_text',
            new_name='syllabus_json',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='courses.courseversion'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('GENED', 'General Education'), ('FOUND', 'Foundation'), ('CORE', 'Core Major'), ('ELECT', 'Elective'), ('CAP', 'Capstone'), ('RES', 'Research')], max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='assessment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='version',
            field=models.CharField(default='v1', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
    ]
