# Generated by Django 5.2.6 on 2025-10-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_created_at_courseversion_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
    ]
