# Generated by Django 5.2.6 on 2025-10-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_learning_outcomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
