# Generated by Django 5.2.6 on 2025-11-25 15:10

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_slug_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
