# Generated by Django 5.2.6 on 2025-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0002_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
