# Generated by Django 5.2.6 on 2025-12-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0004_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
