# Generated by Django 5.2.6 on 2025-10-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_prerequisites_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
