# Generated by Django 5.2.6 on 2025-09-29 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='completion_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='syllabus.collegecourse'),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='course_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='collegedegree',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, null=True, blank=True, related_name='degrees', to='syllabus.college'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='collegedegree',
            unique_together={('college', 'title')},
        ),
    ]
