# Generated by Django 5.2.6 on 2025-09-29 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_college_collegecourse_completion_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegecourse',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.collegesemester'),
        ),
    ]
