# Generated by Django 5.2.6 on 2025-10-03 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_alter_collegedegree_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedegree',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degrees', to='syllabus.college'),
        ),
    ]
