# Generated by Django 5.2.6 on 2025-12-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year', 'number']},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semester',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('degree', 'year', 'number')},
        ),
    ]
