# Generated by Django 5.2.6 on 2025-10-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='base_url',
            field=models.URLField(blank=True),
        ),
    ]
