# Generated by Django 5.2.6 on 2025-09-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_rename_created_at_courseversion_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_id', models.CharField(max_length=20, unique=True)),
                ('discipline', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('ASSOC', 'Associate'), ('BACH', 'Bachelor'), ('MAST', 'Master')], max_length=10)),
                ('exit_requirements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('courses', models.ManyToManyField(related_name='semesters', to='courses.course')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='degrees.degree')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('degree', 'year')},
            },
        ),
    ]
