# Generated by Django 5.2.6 on 2025-09-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('GENED', 'General Education'), ('FOUND', 'Foundation'), ('CORE', 'Core Major'), ('ELECT', 'Elective'), ('CAP', 'Capstone'), ('RES', 'Research')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('ASSOC', 'Associate'), ('BACH', 'Bachelor'), ('MAST', 'Master')], max_length=10)),
                ('overview', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('exit_requirements', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='years', to='syllabus.collegedegree')),
            ],
            options={
                'ordering': ['degree', 'number'],
                'unique_together': {('degree', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CollegeSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('number', models.PositiveSmallIntegerField()),
                ('courses', models.ManyToManyField(related_name='semesters', to='syllabus.collegecourse')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='syllabus.year')),
            ],
            options={
                'ordering': ['year', 'number'],
                'unique_together': {('year', 'number')},
            },
        ),
    ]
