# Generated by Django 5.2.6 on 2025-09-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_collegecourse_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegedegree',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='degrees', to='syllabus.college'),
        ),
    ]
